services:
  db:
    build:
      context: ./Database
      dockerfile: Dockerfile
    container_name: postgres_pgrouting
    environment:
      LANG: en_US.utf8
      LANGUAGE: en_US.utf8
      LC_ALL: en_US.utf8
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: routing
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 5s
      retries: 5


  script-runner:
    image: debian:bullseye-slim
    depends_on:
      db:
        condition: service_healthy
    environment:
      POSTGRES_DB: routing
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./Database/load_osm_data.sh:/script.sh
      - ./wait_for_it.sh:/wait-for-it.sh
    entrypoint: ["sh", "-c", "chmod +x /script.sh && /wait-for-it.sh db:5432 -- sh /script.sh"]
    deploy:
      resources:
        limits:
          memory: 5G
          cpus: "4.0"

       
volumes:
  postgres_data:
