services:
  db:
    build:
      context: ./Database
      dockerfile: Dockerfile
    container_name: postgres_pgrouting
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: routing
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./Database/osm2po:/osm2po
       
volumes:
  postgres_data:
